### ISSUE TITLE
MG_VERSION should be 6.17

### ISSUE THREAD

**Issue by zdila** [mongoose-os-libs/mongoose#3]
`MG_VERSION` is 6.16 but should be 6.17 since mos 2.17.0.

**Comment by zdila** [comment]
Actually manually compilled mongoose 6.16 or 6.17 doesn't work with mos 2.17.0.
Either it is missing `mg_dns_encode_name_s` and `mg_strcasecmp` referenced from `mgos_dns_sd.c` if 6.16 is used or `MG_F_PROTO_1` and `MG_F_MQTT_PING_PENDING` referenced from from `mg_mqtt.c` if 6.17 is used.

**Comment by rojer** [comment]
mongoose.c used in the build is literally the same as the one on the latest dev branch of cesanta/mongoose

**Comment by zdila** [comment]
I see. Thanks. For tagged releases of mongoose-os I think it would be good to tag also mongoose itself so we would know which version dependencies to use.

**Comment by rojer** [comment]
yes, though it's a bit complicated, as they are on different versioning scheme.

**Comment by zdila** [comment]
BTW the only reason we want to compile mongoose by ourselves is #2.
